# Generated by Django 3.2.6 on 2021-08-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrfilecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uploads', models.FileField(upload_to='img/imgs')),
            ],
        ),
    ]
