# Generated by Django 3.2.6 on 2021-08-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0002_qrfilecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrfilecode',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
