# Generated by Django 3.2.6 on 2021-08-07 00:06

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0003_qrfilecode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrfilecode',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='name'),
        ),
    ]
