# Generated by Django 3.2.6 on 2021-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0004_alter_qrfilecode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrfilecode',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
