# Generated by Django 3.2.6 on 2021-08-12 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_gen', '0007_auto_20210812_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='author',
        ),
        migrations.AddField(
            model_name='qrfilecode',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
