# Generated by Django 3.2.6 on 2021-08-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0009_qraudiocode_qrpdfcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='qraudiocode',
            name='uploads',
            field=models.FileField(upload_to='img/audios'),
        ),
        migrations.AlterField(
            model_name='qrpdfcode',
            name='uploads',
            field=models.FileField(upload_to='img/pdfs'),
        ),
    ]
